### ISSUE TITLE
按MC百科上操作添加mod后发现mod可以正常加载但无物品

### ISSUE THREAD

**Issue by EXDoge000** [TunYuntuwuQWQ/addurdisc#1]
Forge1.18.2，放音频文件在文件夹中没有效果，确认是ogg，且文件名不包含其他字符，lang文件夹下没有zh_cn.json，en_us.json是空的,确切的来说assets文件夹下除了sounds文件夹里我自己加的音频文件外，其他东西打开到最后发现都是空的没东西，也可以排除版本隔离问题
![en_us json - 记事本 2024_7_19 16_10_25](https://github.com/user-attachments/assets/cad70a77-7651-45af-866a-027b629450b2)
![item 2024_7_19 16_10_42](https://github.com/user-attachments/assets/97762c57-e970-46ce-b43c-bd7da592b6a7)
![sounds 2024_7_19 16_09_31](https://github.com/user-attachments/assets/07da69fa-8114-4844-9bac-557330850beb)
![sounds 2024_7_19 16_10_12](https://github.com/user-attachments/assets/2c71957b-1bce-456e-af1d-b58b28985110)
[latest.log](https://github.com/user-attachments/files/16309345/latest.log)

**Comment by TunYuntuwuQWQ** [comment]
在游戏设置里的「Java 虚拟机参数」里加 -Dlegacy.debugClassLoading=true -Dlegacy.debugClassLoadingFiner=true -Dlog4j2.formatMsgNoLookups=false ，然后启动游戏，崩溃后发新的崩溃信息 （latest.log）![](https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/2023-04/SuAn2sjIow0md0b6.png )![](https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/2023-06/06kkZoEmeP0m2061.png )![](https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/2023-07/DAVItvJ3Z90mc093.png )![](https://gitcode.net/chearlai/kookfiles/-/raw/master/assets/2023-06/B9zltUBaco08d03p.png)

**Comment by TunYuntuwuQWQ** [comment]
以及建议把音频文件也发过来一份

**Comment by EXDoge000** [comment]
输入了但游戏正常启动没崩溃
这里发不了ogg
![Uploading Hello Minecraft! Launcher v3.5.8 2024_7_19 18_07_15.png…]()

[rugal4.zip](https://github.com/user-attachments/files/16310653/rugal4.zip)

**Comment by TunYuntuwuQWQ** [comment]
> 输入了但游戏正常启动没崩溃
> 这里发不了ogg
> ![Uploading Hello Minecraft! Launcher v3.5.8 2024_7_19 18_07_15.png…]()
> 
> [rugal4.zip](https://github.com/user-attachments/files/16310653/rugal4.zip)
> 

不需要崩溃，这段话术是我复制的 你启动游戏到主页面之后退出再发新的latest就行
另外你图没了

**Comment by EXDoge000** [comment]
[Uploading debug.log…]()
找到了，那个图不需要了

**Comment by TunYuntuwuQWQ** [comment]
> [Uploading debug.log…]()
> 找到了，那个图不需要了

你log也没了

**Comment by EXDoge000** [comment]
[debug.log](https://github.com/user-attachments/files/16310888/debug.log)
因为我这边儿联git信号很不稳（

**Comment by TunYuntuwuQWQ** [comment]
> [debug.log](https://github.com/user-attachments/files/16310888/debug.log)
> 因为我这边儿联git信号很不稳（

日志看起来ogg已经被正常注册了..你可以尝试禁用掉其他所有mod再试一次吗

**Comment by EXDoge000** [comment]
另开了一个游戏，只有这个和forge，还是一样的问题

**Comment by EXDoge000** [comment]
我这儿已经卡的发不了图了

**Comment by TunYuntuwuQWQ** [comment]
> 另开了一个游戏，只有这个和forge，还是一样的问题

麻烦同样发一下debug日志

**Comment by TunYuntuwuQWQ** [comment]
> > 另开了一个游戏，只有这个和forge，还是一样的问题
> 
> 麻烦同样发一下debug日志

我现在手头上没有电脑，晚一些才能测试

**Comment by EXDoge000** [comment]
好了，重启了三次出来了
[debug.log](https://github.com/user-attachments/files/16311337/debug.log)
[debug.log](https://github.com/user-attachments/files/16311343/debug.log)

**Comment by EXDoge000** [comment]
而且两个包都正常了

**Comment by TunYuntuwuQWQ** [comment]
> 而且两个包都正常了

日志看不出什么问题..但是问题莫名其妙解决了？

**Comment by EXDoge000** [comment]
是这样，重启第三遍什么也没改，之前加的那一个音频突然就出来了，对应的那些文件里也能看到相关信息了

**Comment by TunYuntuwuQWQ** [comment]
> 是这样，重启第三遍什么也没改，之前加的那一个音频突然就出来了，对应的那些文件里也能看到相关信息了

我之后会再测试一下的,现在确实不清楚是什么问题.我将关闭此issue，如果测试有新发现，我会新开一个issue

**Comment by TunYuntuwuQWQ** [comment]
抱歉，实在未能复现出问题，也没什么头绪，只能暂时搁置了，如果您有新的发现欢迎发起新的issue进行讨论

**Comment by EXDoge000** [comment]
后面又试了几次，基本没再出问题了，发现可能要么进游戏先挂机什么不做多等一会儿，要么直接重启游戏，添加的东西就正常出来了，但直接用指令重新加载游戏资源就不行

**Comment by TunYuntuwuQWQ** [comment]
> 后面又试了几次，基本没再出问题了，发现可能要么进游戏先挂机什么不做多等一会儿，要么直接重启游戏，添加的东西就正常出来了，但直接用指令重新加载游戏资源就不行

模组的所有行为都应该在启动游戏过程中完成，进入主页后应该不会再有什么操作了，所以对于多等一会有效我也没什么头绪，指令重载资源不兼容此模组，也不太可能兼容，Forge并不能热注册，也就是新物品注册只能在游戏启动过程中，所以修改后只能重启游戏。
