### ISSUE TITLE
按MC百科上操作添加mod后发现mod可以正常加载但无物品

### ISSUE THREAD

**Issue by haicha0** [TunYuntuwuQWQ/addurdisc#2]
版本1.20.1 fabric 将音频文件放入指定文件夹没用效果
跟之前提出问题的人问题一样
![5](https://github.com/user-attachments/assets/40ef2409-04bf-4f52-acf7-cd7a70dad70a)
![6](https://github.com/user-attachments/assets/55657fe8-e399-4b9e-9376-48bd172da285)
![7](https://github.com/user-attachments/assets/2720d1fa-50d7-4771-a764-99a6fe386208)
![1](https://github.com/user-attachments/assets/377212f1-9e51-4682-9fd1-fb81f3d7352a)
![2](https://github.com/user-attachments/assets/d0f99427-4e7e-4248-9076-f18b8eb14736)
![3](https://github.com/user-attachments/assets/f762e9c1-12b2-4fc6-be07-dde06c63f706)
![4](https://github.com/user-attachments/assets/3cdf459b-e3c4-4642-ae03-2e23498802dd)
![8](https://github.com/user-attachments/assets/3eb6d06c-53c2-4825-9e8b-8c958bf9f723)
[在银河中孤独摇摆.zip](https://github.com/user-attachments/files/16530311/default.zip)
ogg文件发不了我改成zip后缀，作者大大可以看看

**Comment by TunYuntuwuQWQ** [comment]
音频文件文件名不能有小写字母、数字、“-._”以外的字符，有的话这个音频文件会被忽略，中文也在排除范围内哟，改一下文件名应该就行了

**Comment by haicha0** [comment]
解决了谢谢作者
